// Generated by CoffeeScript 1.7.1
(function() {
  var LODASH, TRM, alert, badge, debug, echo, help, info, js_type_of, log, new_, options, praise, rpr, urge, warn, whisper,
    __slice = [].slice;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'jsEq/jseq';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  praise = TRM.get_logger('praise', badge);

  echo = TRM.echo.bind(TRM);

  LODASH = require('lodash');

  options = {
    'signed-zeroes': false,
    'functions': true,
    'NaN': true,
    'array-attributes': true
  };

  js_type_of = function(x) {
    return Object.prototype.toString.call(x);
  };

  new_ = function(options_or_handler, self) {
    var eq, handler, properties_are_equal, settings;
    if ((js_type_of(options_or_handler)) === '[object Function]') {
      handler = options_or_handler;
      settings = options;
    } else {
      settings = LODASH.merge({}, options, options_or_handler != null ? options_or_handler : {});
      handler = null;
    }
    properties_are_equal = function(a, b, all) {
      var name, pa, pb, value;
      if (all == null) {
        all = true;
      }

      /* TAINT should we check for property descriptors? */
      pa = {};
      for (name in a) {
        value = a[name];
        if (all || !((0 <= name && name < a.length))) {
          pa[name] = value;
        }
      }
      pb = {};
      for (name in b) {
        value = b[name];
        if (all || !((0 <= name && name < b.length))) {
          pb[name] = value;
        }
      }
      whisper(pa, pb);
      return eq(pa, pb);
    };
    return eq = function() {
      var P, R, arity, idx, _i, _ref;
      P = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if ((arity = P.length) < 2) {
        throw new Error("need at least 2 arguments, got " + arity);
      } else {
        R = true;
        for (idx = _i = 1, _ref = P.length; 1 <= _ref ? _i < _ref : _i > _ref; idx = 1 <= _ref ? ++_i : --_i) {
          R = R && LODASH.isEqual(P[0], P[idx], function(a, b) {
            if (handler != null) {
              return handler(a, b);
            }
            if (a === 0 && b === 0 && settings['signed-zeroes']) {

              /* taken verbatim from lodash: */
              return !a !== 0 || (1 / a == 1 / b );
            }
            if (settings['functions']) {
              if (('[object Function]' === js_type_of(a)) && ('[object Function]' === js_type_of(b))) {
                if (a.toString() !== b.toString()) {
                  return false;
                }
                return properties_are_equal(a, b, true);
              }
            }
            if (!settings['NaN']) {

              /* isNaN is broken as per MDN, so we don't use it */
              if ((a !== a) && (b !== b)) {
                return false;
              }
            }
            if (settings['array-attributes']) {
              if (('[object Array]' === js_type_of(a)) && ('[object Array]' === js_type_of(b))) {
                if (a.length !== b.length) {
                  return false;
                }
                if (!properties_are_equal(a, b, false)) {
                  return false;
                }
                return LODASH.isEqual(a, b);
              }
            }
            return void 0;
          });
          if (!R) {
            return R;
          }
        }
        return R;
      }
    };
  };

  module.exports = new_();

  module.exports["new"] = new_;

}).call(this);
